services:
  
  # Serviço para o PostgreSQL
  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
